spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

#cloud:
#  aws:
#    credentials:
#      access-key: ${AWS_ACCESS_KEY}
#      secret-key: ${AWS_SECRET_KEY}
#    region:
#      static: ${AWS_REGION}
#    s3:
#      bucket: ${AWS_S3_BUCKET}